#!/usr/bin/bash

IWTL_DIR="/usr/share/iwtl"
IWTL_QUOTES="${IWTL_DIR}/quotes"
IWTL_TOME="/home/${USER}/.tome"

if [ ! -f $IWTL_TOME ]; then IWTL_TOME="${IWTL_DIR}/tome"; fi;

IWTL_FILE="/home/${USER}/.iwtl"

[ -f $IWTL_FILE ] || printf "Last added: \nLast suggested:\n" > $IWTL_FILE
LAST_NUMBER=$(($(tail -n 1 $IWTL_FILE | cut -d " " -f1) + 1))

usage()
{
    echo "iwtl (I Want To Learn)"
    echo "Simple bash script and task randomizer for curious-lazy people"
    echo
    echo "Syntax: iwtl [add|list|random|complete|delete|find]"
    echo "options:"
    echo "add        Add a new task to the tasklist"
    echo "list       See all existing tasks and taskid's"
    echo "random     Get a random task from your tasklist"
    echo "complete   Complete a task. Removes it from the tasklist"
    echo "delete     Delete a task (forever)"
    echo "find       Find a task in the tasklist"
    echo
}

add()
{
    task="$LAST_NUMBER ${1}"
    echo $task >> ${IWTL_FILE}
    echo "'$1' added. Good luck completing it!"
    echo "Task ID: $LAST_NUMBER"
    sed -i "1s/.*/Last added: ${task}/" $IWTL_FILE
}

list()
{
    cat $IWTL_FILE
}

if [[ -z "$1" ]]; then usage && exit 1; fi;
if [[ "$1" == "random" ]]
then
    task=$(list|tail -n +3|shuf -n 1)
    echo "Here's a new task for you:"
    echo "    $task"
    sed -i "2s/.*/Last suggested: ${task}/" $IWTL_FILE
    exit 1
fi
if [[ "$1" == "list" ]]
then
    list
    exit 1
fi
if [[ -z "$2" ]]; then usage && exit 1; fi;
if [[ "$1" == "add" ]]
then
    add "$2"; exit 1
fi
if [[ "$1" == 'find' ]]
then
    list | grep -i "$2"
    exit 1
fi

task_id=$(($2 + 2))
task=$(sed "${task_id}q;d" ${IWTL_FILE})

if [[ -z "$task" ]]; then echo "Error: Task doesn't exist. Try 'iwtl find'." && exit 1; fi;
if [[ "$1" == "complete" ]]
then
    echo "Task: $task"
    read -p "Are you sure you have completed this? [y/N]:" -n 1
    echo
    if ! [[ $REPLY =~ ^[Yy]$ ]]; then echo "Hmm... come back when you are done." && exit 1; fi;

    sed -i "${task_id}d" ${IWTL_FILE}
    echo =============================================
    sed -e "s/\$USER/${USER}/" ${IWTL_QUOTES} |shuf -n 1| cowsay -f $(shuf -n 1 -e $(cowsay -l | tail -n +2)) 
    echo =============================================
    echo "Completed task: $task"
    cat ${IWTL_TOME}|shuf -n 1
    echo =============================================
    exit 1
fi
if [[ "$1" == "delete" ]]
then
    echo "Task: $task"
    read -p "Are you sure you want to delete this task? [y/N]:" -n 1
    echo
    if ! [[ $REPLY =~ ^[Yy]$ ]]; then exit 1; fi;
    sed -i "${task_id}d" ${IWTL_FILE}
    echo "Task deleted. I hope you know what you're doing."
    exit 1
fi
